# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(615, 533)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 472, 416))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(1000000, 50))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        self.sendButton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sendButton.setFont(font)
        self.sendButton.setText("")
        self.sendButton.setCheckable(False)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_2.addWidget(self.sendButton)
        self.horizontalLayout_2.setStretch(0, 10)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 500)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #---self-config---#

        self.sendButton.setStyleSheet("QPushButton{border-image: url(send.png)}"
                                  "QPushButton:hover{border-image: url(send.png)}" 
                                  "QPushButton:pressed{border-image: url(on_send.png)}")

        self.msg_count = 0
        self.text_history = []

        # self.formLayout = QtWidgets.QFormLayout()

        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setHorizontalSpacing(2)
        self.gridlayout.setVerticalSpacing(5)

        self.groupBox = QtWidgets.QGroupBox()

        self.sendButton.clicked.connect(self.on_send)
        self.pushButton.clicked.connect(self.on_clear)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Back"))

    def on_send(self):
        msg = self.inputMessage.toPlainText()
        self.inputMessage.setText("")
        if(msg==''):
            return

        self.send_message(0,msg)
        self.send_message(1,"yes")
        
    def on_clear(self):
        print(self.gridlayout.count())
        
        for i in range(self.gridlayout.count()):
            if(self.gridlayout.itemAt(i).widget()):
                self.gridlayout.itemAt(i).widget().deleteLater()

        self.groupBox.setLayout(self.gridlayout)
        self.scrollArea.setWidget(self.groupBox)

        self.msg_count = 0

    def send_message(self,who,msg):
        # who==0 -> usr
        if(who):
            photo_path = 'bot.png'
        else:
            photo_path = 'user.jpg'

        photo = QLabel()
        pixmap = QPixmap(photo_path)
        smaller_pixmap = pixmap.scaled(80, 80, QtCore.Qt.KeepAspectRatio, QtCore.Qt.FastTransformation)
        photo.setPixmap(smaller_pixmap)
        
        text = QLabel()
        font = QtGui.QFont()
        font.setPointSize(20)
        text.setFont(font)
        text.setText(msg)
        text.setWordWrap(True)

        pos = QLabel()
        pos.setText(" ")
        
        
        Hbox = QtWidgets.QHBoxLayout()
        Hbox.setSpacing(10)

        if(who):
            
            Hbox.addWidget(photo)
            Hbox.addWidget(text)
            
            self.text_history.append(Hbox)
            self.gridlayout.addLayout(Hbox,self.msg_count,0,alignment=QtCore.Qt.AlignLeft)
            self.gridlayout.addWidget(pos,self.msg_count,1,alignment=QtCore.Qt.AlignCenter)
        else:
            
            Hbox.addWidget(text)
            Hbox.addWidget(photo)
            self.text_history.append(Hbox)
            self.gridlayout.addWidget(pos,self.msg_count,0,alignment=QtCore.Qt.AlignCenter)
            self.gridlayout.addLayout(Hbox,self.msg_count,1,alignment=QtCore.Qt.AlignRight)

            
        
        self.groupBox.setLayout(self.gridlayout)
        self.scrollArea.setWidget(self.groupBox)
        
        
        self.msg_count += 1