# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_interface_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import time
import configparser

config = configparser.ConfigParser()

def setConfig():
    with open('config.ini', 'w') as configfile:
        config.write(configfile)

class Ui_MainWindow(QtWidgets.QWidget):

    switch_window = QtCore.pyqtSignal()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(615, 533)
        icon = QtGui.QPixmap(config['database']['bot_image'])
        icon = icon.scaled(200,200)
        MainWindow.setWindowIcon(QtGui.QIcon(icon))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setMinimumSize(QtCore.QSize(80 , 80))
        self.backButton.setObjectName("backButton")
        self.backButton.setText("")
        self.verticalLayout_3.addWidget(self.backButton)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 458, 416))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inputMessage = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputMessage.sizePolicy().hasHeightForWidth())
        self.inputMessage.setSizePolicy(sizePolicy)
        self.inputMessage.setMaximumSize(QtCore.QSize(1000000, 60))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(18)
        self.inputMessage.setFont(font)
        self.inputMessage.setObjectName("inputMessage")
        self.horizontalLayout_2.addWidget(self.inputMessage)
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        self.sendButton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sendButton.setFont(font)
        self.sendButton.setText("")
        self.sendButton.setCheckable(False)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_2.addWidget(self.sendButton)
        self.horizontalLayout_2.setStretch(0, 10)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 500)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #---self-config---#

        self.sendButton.setStyleSheet("QPushButton{border-image: url(./img/send.png)}"
                                  "QPushButton:hover{border-image: url(./img/send.png)}" 
                                  "QPushButton:pressed{border-image: url(./img/on_send.png)}")
        self.backButton.setStyleSheet("QPushButton{border-image: url(./img/back.png)}"
                                  "QPushButton:hover{border-image: url(./img/back.png)}" 
                                  "QPushButton:pressed{border-image: url(./img/back.png)}")
        

        self.msg_count = 0
        self.text_history = []
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setHorizontalSpacing(2)
        self.gridlayout.setVerticalSpacing(5)

        self.groupBox = QtWidgets.QGroupBox()

        self.sendButton.clicked.connect(self.on_send)
        self.backButton.clicked.connect(self.on_back)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backButton.setText(_translate("MainWindow", "Back"))
    
    def on_send(self):
        msg = self.inputMessage.toPlainText()
        self.inputMessage.setText("")
        if(msg==''):
            return

        self.send_message(0,msg)
        self.statusbar.showMessage("bot正在輸入...",2000)
        loop = QtCore.QEventLoop()
        QtCore.QTimer.singleShot(2000, loop.quit)
        loop.exec_()
        try:
            self.send_message(1,config["chat"][msg])
        except:
            self.send_message(1,"Error")
        

    def send_message(self,who,msg):
        # who==0 -> usr
        if(who):
            photo_path = config['database']['bot_image']
        else:
            photo_path = config['database']['user_image']

        photo = QLabel()
        pixmap = QPixmap(photo_path)
        smaller_pixmap = pixmap.scaled(80, 80, QtCore.Qt.KeepAspectRatio, QtCore.Qt.FastTransformation)
        photo.setPixmap(smaller_pixmap)
        
        text = QLabel()
        font = QtGui.QFont()
        font.setPointSize(20)
        text.setFont(font)
        text.setText(msg)
        text.setWordWrap(True)

        pos = QLabel()
        pos.setText(" ")
        
        Hbox = QtWidgets.QHBoxLayout()
        Hbox.setSpacing(10)

        if(who):
            Hbox.addWidget(photo)
            Hbox.addWidget(text)
            self.text_history.append(Hbox)
            self.gridlayout.addLayout(Hbox,self.msg_count,0,alignment=QtCore.Qt.AlignLeft)
            self.gridlayout.addWidget(pos,self.msg_count,1,alignment=QtCore.Qt.AlignCenter)
        else:
            Hbox.addWidget(text)
            Hbox.addWidget(photo)
            self.text_history.append(Hbox)
            self.gridlayout.addWidget(pos,self.msg_count,0,alignment=QtCore.Qt.AlignCenter)
            self.gridlayout.addLayout(Hbox,self.msg_count,1,alignment=QtCore.Qt.AlignRight)

        self.groupBox.setLayout(self.gridlayout)
        self.scrollArea.setWidget(self.groupBox)
        self.msg_count += 1
    
    def on_back(self):
        self.switch_window.emit()

class Ui_Digital_Immortality(QtWidgets.QWidget):

    switch_window_to_main = QtCore.pyqtSignal()
    switch_window_to_setting = QtCore.pyqtSignal()
    
    def setupUi(self, Digital_Immortality):
        config.read("config.ini")

        Digital_Immortality.setObjectName("Digital_Immortality")
        Digital_Immortality.resize(576, 444)
        icon = QtGui.QPixmap(config['database']['app_icon'])
        icon = icon.scaled(64,64)
        Digital_Immortality.setWindowIcon(QtGui.QIcon(icon))
        self.centralwidget = QtWidgets.QWidget(Digital_Immortality)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ICON = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ICON.sizePolicy().hasHeightForWidth())
        self.ICON.setSizePolicy(sizePolicy)
        self.ICON.setMaximumSize(QtCore.QSize(16777215, 200))
        self.ICON.setText("")
        Appimg = QtGui.QPixmap(config['database']['bot_image'])
        Appimg = Appimg.scaled(200,200)
        self.ICON.setPixmap(QtGui.QPixmap(Appimg))
        self.ICON.setAlignment(QtCore.Qt.AlignCenter)
        self.ICON.setObjectName("ICON")
        self.verticalLayout.addWidget(self.ICON)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.chooseButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.chooseButton.setObjectName("chooseButton")
        self.verticalLayout.addWidget(self.chooseButton)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setEnabled(False)
        self.startButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.startButton.setCheckable(False)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.settingButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.settingButton.setObjectName("settingButton")
        self.verticalLayout.addWidget(self.settingButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Digital_Immortality.setCentralWidget(self.centralwidget)

        self.retranslateUi(Digital_Immortality)
        QtCore.QMetaObject.connectSlotsByName(Digital_Immortality)

        #----self-config----#

        if(config['database']['model']!=""):
            self.startButton.setEnabled(True)
        else:
            self.startButton.setEnabled(False)

        self.chooseButton.clicked.connect(self.on_choose_file)
        self.startButton.clicked.connect(self.on_start)
        self.settingButton.clicked.connect(self.on_setting)
        
    def retranslateUi(self, Digital_Immortality):
        _translate = QtCore.QCoreApplication.translate
        Digital_Immortality.setWindowTitle(_translate("Digital_Immortality", "Digital Immortality"))
        self.label.setText(_translate("Digital_Immortality", "Digital Immortality"))
        self.chooseButton.setText(_translate("Digital_Immortality", "選擇檔案"))
        self.startButton.setText(_translate("Digital_Immortality", "開始"))
        self.settingButton.setText(_translate("Digital_Immortality", "設定"))
        
    
    def on_choose_file(self):
        data_path, _ = QFileDialog.getOpenFileName(None, 'Open File', r"/home", "All Files (*)")
        if data_path:
            config['database']['model']=data_path
            setConfig()
            self.startButton.setEnabled(True)
    
    def on_start(self):
        self.switch_window_to_main.emit()
    
    def on_setting(self):
        self.switch_window_to_setting.emit()
        
class Ui_Setting(QtWidgets.QWidget):

    switch_window = QtCore.pyqtSignal()

    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.resize(500, 200)
        icon = QtGui.QPixmap(config['database']['setting_icon'])
        icon = icon.scaled(200,200)
        Setting.setWindowIcon(QtGui.QIcon(icon))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Setting.sizePolicy().hasHeightForWidth())
        Setting.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        Setting.setFont(font)
        Setting.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Setting.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(Setting)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botImage = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botImage.sizePolicy().hasHeightForWidth())
        self.botImage.setSizePolicy(sizePolicy)
        self.botImage.setMaximumSize(QtCore.QSize(16777215, 30))
        self.botImage.setObjectName("botImage")
        self.horizontalLayout.addWidget(self.botImage)
        self.chooseButton1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseButton1.sizePolicy().hasHeightForWidth())
        self.chooseButton1.setSizePolicy(sizePolicy)
        self.chooseButton1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.chooseButton1.setObjectName("chooseButton1")
        self.horizontalLayout.addWidget(self.chooseButton1)
        self.botImagePath = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botImagePath.sizePolicy().hasHeightForWidth())
        self.botImagePath.setSizePolicy(sizePolicy)
        self.botImagePath.setMaximumSize(QtCore.QSize(16777215, 30))
        self.botImagePath.setAlignment(QtCore.Qt.AlignCenter)
        self.botImagePath.setObjectName("botImagePath")
        self.horizontalLayout.addWidget(self.botImagePath)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.userImage = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userImage.sizePolicy().hasHeightForWidth())
        self.userImage.setSizePolicy(sizePolicy)
        self.userImage.setMaximumSize(QtCore.QSize(16777215, 30))
        self.userImage.setObjectName("userImage")
        self.horizontalLayout_2.addWidget(self.userImage)
        self.chooseButton2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseButton2.sizePolicy().hasHeightForWidth())
        self.chooseButton2.setSizePolicy(sizePolicy)
        self.chooseButton2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.chooseButton2.setObjectName("chooseButton2")
        self.horizontalLayout_2.addWidget(self.chooseButton2)
        self.userImagePath = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userImagePath.sizePolicy().hasHeightForWidth())
        self.userImagePath.setSizePolicy(sizePolicy)
        self.userImagePath.setMaximumSize(QtCore.QSize(16777215, 30))
        self.userImagePath.setAlignment(QtCore.Qt.AlignCenter)
        self.userImagePath.setObjectName("userImagePath")
        self.horizontalLayout_2.addWidget(self.userImagePath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setMaximumSize(QtCore.QSize(100, 40))
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_3.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setMaximumSize(QtCore.QSize(100, 40))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_3.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Setting.setCentralWidget(self.centralwidget)

        self.retranslateUi(Setting)
        QtCore.QMetaObject.connectSlotsByName(Setting)

        #---self-config---#
        self.userImagePath.setText(config['database']["user_image"])
        self.botImagePath.setText(config['database']["bot_image"])
        self.okButton.clicked.connect(self.on_ok)
        self.cancelButton.clicked.connect(self.on_cancel)
        self.chooseButton2.clicked.connect(self.on_usrImg)
        self.chooseButton1.clicked.connect(self.on_botImg)

    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "設定"))
        self.botImage.setText(_translate("Setting", "機器人照片："))
        self.chooseButton1.setText(_translate("Setting", "選擇檔案"))
        self.botImagePath.setText(_translate("Setting", "Path"))
        self.userImage.setText(_translate("Setting", "使用者照片："))
        self.chooseButton2.setText(_translate("Setting", "選擇檔案"))
        self.userImagePath.setText(_translate("Setting", "Path"))
        self.okButton.setText(_translate("Setting", "確認"))
        self.cancelButton.setText(_translate("Setting", "取消"))
    
    def on_ok(self):
        setConfig()
        self.switch_window.emit()
    
    def on_cancel(self):
        self.switch_window.emit()
    
    def on_usrImg(self):
        data_path, _ = QFileDialog.getOpenFileName(None, 'Open File', r"/home", "All Files (*)")
        if data_path:
            config['database']['user_image']=data_path
            setConfig()
            self.userImagePath.setText(data_path)
            #optimize: check if it's a image
    
    def on_botImg(self):
        data_path, _ = QFileDialog.getOpenFileName(None, 'Open File', r"/home", "All Files (*)")
        if data_path:
            config['database']['bot_image']=data_path
            setConfig()
            self.botImagePath.setText(data_path)
            #optimize: check if it's a image

            

class Controller:

    def __init__(self):
        pass

    def start_ui(self):
        self.StartWindow = QtWidgets.QMainWindow()
        self.start = Ui_Digital_Immortality()
        self.start.setupUi(self.StartWindow)
        self.start.switch_window_to_main.connect(self.main_ui)
        self.start.switch_window_to_setting.connect(self.set_ui)
        self.StartWindow.show()

    def main_ui(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.main = Ui_MainWindow()
        self.main.setupUi(self.MainWindow)
        self.main.switch_window.connect(self.Mainback2Start_ui)
        self.StartWindow.close()
        self.MainWindow.show()

    def set_ui(self):

        self.SetWindow = QtWidgets.QMainWindow()
        self.set = Ui_Setting()
        self.set.setupUi(self.SetWindow)
        self.set.switch_window.connect(self.Setback2Start_ui)
        self.StartWindow.close()
        self.SetWindow.show()
    
    def Mainback2Start_ui(self):
        self.StartWindow = QtWidgets.QMainWindow()
        self.start = Ui_Digital_Immortality()
        self.start.setupUi(self.StartWindow)
        self.start.switch_window_to_main.connect(self.main_ui)
        self.start.switch_window_to_setting.connect(self.set_ui)
        self.MainWindow.close()
        self.StartWindow.show()
    
    def Setback2Start_ui(self):
        self.StartWindow = QtWidgets.QMainWindow()
        self.start = Ui_Digital_Immortality()
        self.start.setupUi(self.StartWindow)
        self.start.switch_window_to_main.connect(self.main_ui)
        self.start.switch_window_to_setting.connect(self.set_ui)
        self.SetWindow.close()
        self.StartWindow.show()
        
    
    

    



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    controller = Controller()
    controller.start_ui()

    sys.exit(app.exec_())
